### ISSUE TITLE
[typo] Typo in repo

### ISSUE THREAD

**Issue by LunaQu4kez** [chanbengz/SUSTech_CS_Notes#1]
Typo in `README_ZH.md -> 如何利用本项目学习 -> DON'T`
```
不要不停课，即使你都学会了。
```
Modify to
```
不要不听课，即使你都学会了。
```

**Comment by LunaQu4kez** [comment]
Typo警察👮‍

**Comment by chanbengz** [comment]
Please create a pull request and directly modify the code. Thx for the contribution.
